// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Do not modify this file. This file is machine generated, and any changes to it will be overwritten.
// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

#[allow(dead_code)]
pub fn to_dafny(
    value: &aws_sdk_dynamodb::types::BatchStatementError,
) -> ::std::rc::Rc<crate::r#software::amazon::cryptography::services::dynamodb::internaldafny::types::BatchStatementError>{
    ::std::rc::Rc::new(
    crate::r#software::amazon::cryptography::services::dynamodb::internaldafny::types::BatchStatementError::BatchStatementError {
        Code: ::std::rc::Rc::new(match &value.code {
    Some(x) => crate::Wrappers::Option::Some { value: crate::ddb::conversions::batch_statement_error_code_enum::to_dafny(x.clone()) },
    None => crate::Wrappers::Option::None { }
})
,
 Message: crate::ddb::standard_library_conversions::ostring_to_dafny(&value.message),
    }
  )
}
#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        crate::r#software::amazon::cryptography::services::dynamodb::internaldafny::types::BatchStatementError,
    >,
) -> aws_sdk_dynamodb::types::BatchStatementError {
    aws_sdk_dynamodb::types::BatchStatementError::builder()
        .set_code(match &**dafny_value.Code() {
            crate::Wrappers::Option::Some { value } => {
                Some(crate::ddb::conversions::batch_statement_error_code_enum::from_dafny(value))
            }
            _ => None,
        })
        .set_message(
            crate::ddb::standard_library_conversions::ostring_from_dafny(
                dafny_value.Message().clone(),
            ),
        )
        .build()
}
