// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Do not modify this file. This file is machine generated, and any changes to it will be overwritten.
// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

#[allow(dead_code)]
pub fn to_dafny(
    value: &aws_sdk_dynamodb::types::ReplicaGlobalSecondaryIndexDescription,
) -> ::std::rc::Rc<crate::r#software::amazon::cryptography::services::dynamodb::internaldafny::types::ReplicaGlobalSecondaryIndexDescription>{
    ::std::rc::Rc::new(
    crate::r#software::amazon::cryptography::services::dynamodb::internaldafny::types::ReplicaGlobalSecondaryIndexDescription::ReplicaGlobalSecondaryIndexDescription {
        IndexName: crate::ddb::standard_library_conversions::ostring_to_dafny(&value.index_name),
 ProvisionedThroughputOverride: ::std::rc::Rc::new(match &value.provisioned_throughput_override {
    Some(x) => crate::Wrappers::Option::Some { value: crate::ddb::conversions::provisioned_throughput_override::to_dafny(&x) },
    None => crate::Wrappers::Option::None { }
})
,
    }
  )
}
#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        crate::r#software::amazon::cryptography::services::dynamodb::internaldafny::types::ReplicaGlobalSecondaryIndexDescription,
    >,
) -> aws_sdk_dynamodb::types::ReplicaGlobalSecondaryIndexDescription {
    aws_sdk_dynamodb::types::ReplicaGlobalSecondaryIndexDescription::builder()
        .set_index_name(
            crate::ddb::standard_library_conversions::ostring_from_dafny(
                dafny_value.IndexName().clone(),
            ),
        )
        .set_provisioned_throughput_override(
            match (*dafny_value.ProvisionedThroughputOverride()).as_ref() {
                crate::Wrappers::Option::Some { value } => Some(
                    crate::ddb::conversions::provisioned_throughput_override::from_dafny(
                        value.clone(),
                    ),
                ),
                _ => None,
            },
        )
        .build()
}
