// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Do not modify this file. This file is machine generated, and any changes to it will be overwritten.
// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

#[allow(dead_code)]
pub fn to_dafny(
    value: &aws_sdk_dynamodb::types::SseDescription,
) -> ::std::rc::Rc<crate::r#software::amazon::cryptography::services::dynamodb::internaldafny::types::SSEDescription>{
    ::std::rc::Rc::new(
    crate::r#software::amazon::cryptography::services::dynamodb::internaldafny::types::SSEDescription::SSEDescription {
        Status: ::std::rc::Rc::new(match &value.status {
    Some(x) => crate::Wrappers::Option::Some { value: crate::ddb::conversions::sse_status::to_dafny(x.clone()) },
    None => crate::Wrappers::Option::None { }
})
,
 SSEType: ::std::rc::Rc::new(match &value.sse_type {
    Some(x) => crate::Wrappers::Option::Some { value: crate::ddb::conversions::sse_type::to_dafny(x.clone()) },
    None => crate::Wrappers::Option::None { }
})
,
 KMSMasterKeyArn: crate::ddb::standard_library_conversions::ostring_to_dafny(&value.kms_master_key_arn),
 InaccessibleEncryptionDateTime: crate::ddb::standard_library_conversions::otimestamp_to_dafny(&value.inaccessible_encryption_date_time),
    }
  )
}
#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        crate::r#software::amazon::cryptography::services::dynamodb::internaldafny::types::SSEDescription,
    >,
) -> aws_sdk_dynamodb::types::SseDescription {
    aws_sdk_dynamodb::types::SseDescription::builder()
        .set_status(match &**dafny_value.Status() {
            crate::Wrappers::Option::Some { value } => {
                Some(crate::ddb::conversions::sse_status::from_dafny(value))
            }
            _ => None,
        })
        .set_sse_type(match &**dafny_value.SSEType() {
            crate::Wrappers::Option::Some { value } => {
                Some(crate::ddb::conversions::sse_type::from_dafny(value))
            }
            _ => None,
        })
        .set_kms_master_key_arn(
            crate::ddb::standard_library_conversions::ostring_from_dafny(
                dafny_value.KMSMasterKeyArn().clone(),
            ),
        )
        .set_inaccessible_encryption_date_time(
            crate::ddb::standard_library_conversions::otimestamp_from_dafny(
                dafny_value.InaccessibleEncryptionDateTime().clone(),
            ),
        )
        .build()
}
