// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Do not modify this file. This file is machine generated, and any changes to it will be overwritten.
// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

#[allow(dead_code)]
pub fn to_dafny(
    value: &aws_sdk_dynamodb::types::TableClassSummary,
) -> ::std::rc::Rc<crate::r#software::amazon::cryptography::services::dynamodb::internaldafny::types::TableClassSummary>{
    ::std::rc::Rc::new(
    crate::r#software::amazon::cryptography::services::dynamodb::internaldafny::types::TableClassSummary::TableClassSummary {
        TableClass: ::std::rc::Rc::new(match &value.table_class {
    Some(x) => crate::Wrappers::Option::Some { value: crate::ddb::conversions::table_class::to_dafny(x.clone()) },
    None => crate::Wrappers::Option::None { }
})
,
 LastUpdateDateTime: crate::ddb::standard_library_conversions::otimestamp_to_dafny(&value.last_update_date_time),
    }
  )
}
#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        crate::r#software::amazon::cryptography::services::dynamodb::internaldafny::types::TableClassSummary,
    >,
) -> aws_sdk_dynamodb::types::TableClassSummary {
    aws_sdk_dynamodb::types::TableClassSummary::builder()
        .set_table_class(match &**dafny_value.TableClass() {
            crate::Wrappers::Option::Some { value } => {
                Some(crate::ddb::conversions::table_class::from_dafny(value))
            }
            _ => None,
        })
        .set_last_update_date_time(
            crate::ddb::standard_library_conversions::otimestamp_from_dafny(
                dafny_value.LastUpdateDateTime().clone(),
            ),
        )
        .build()
}
