// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Do not modify this file. This file is machine generated, and any changes to it will be overwritten.
impl crate::client::Client {
    /// Constructs a fluent builder for the [`CreateCustomKeyStore`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`cloud_hsm_cluster_id(impl Into<Option<::std::string::String>>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::cloud_hsm_cluster_id) / [`set_cloud_hsm_cluster_id(Option<::std::string::String>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::set_cloud_hsm_cluster_id): (undocumented)<br>
    ///   - [`custom_key_store_name(impl Into<Option<::std::string::String>>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::custom_key_store_name) / [`set_custom_key_store_name(Option<::std::string::String>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::set_custom_key_store_name): (undocumented)<br>
    ///   - [`custom_key_store_type(impl Into<Option<kms::types::CustomKeyStoreType>>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::custom_key_store_type) / [`set_custom_key_store_type(Option<kms::types::CustomKeyStoreType>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::set_custom_key_store_type): (undocumented)<br>
    ///   - [`key_store_password(impl Into<Option<::std::string::String>>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::key_store_password) / [`set_key_store_password(Option<::std::string::String>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::set_key_store_password): (undocumented)<br>
    ///   - [`trust_anchor_certificate(impl Into<Option<::std::string::String>>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::trust_anchor_certificate) / [`set_trust_anchor_certificate(Option<::std::string::String>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::set_trust_anchor_certificate): (undocumented)<br>
    ///   - [`xks_proxy_authentication_credential(impl Into<Option<kms::types::XksProxyAuthenticationCredentialType>>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::xks_proxy_authentication_credential) / [`set_xks_proxy_authentication_credential(Option<kms::types::XksProxyAuthenticationCredentialType>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::set_xks_proxy_authentication_credential): (undocumented)<br>
    ///   - [`xks_proxy_connectivity(impl Into<Option<kms::types::XksProxyConnectivityType>>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::xks_proxy_connectivity) / [`set_xks_proxy_connectivity(Option<kms::types::XksProxyConnectivityType>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::set_xks_proxy_connectivity): (undocumented)<br>
    ///   - [`xks_proxy_uri_endpoint(impl Into<Option<::std::string::String>>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::xks_proxy_uri_endpoint) / [`set_xks_proxy_uri_endpoint(Option<::std::string::String>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::set_xks_proxy_uri_endpoint): (undocumented)<br>
    ///   - [`xks_proxy_uri_path(impl Into<Option<::std::string::String>>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::xks_proxy_uri_path) / [`set_xks_proxy_uri_path(Option<::std::string::String>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::set_xks_proxy_uri_path): (undocumented)<br>
    ///   - [`xks_proxy_vpc_endpoint_service_name(impl Into<Option<::std::string::String>>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::xks_proxy_vpc_endpoint_service_name) / [`set_xks_proxy_vpc_endpoint_service_name(Option<::std::string::String>)`](crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::set_xks_proxy_vpc_endpoint_service_name): (undocumented)<br>
    /// - On success, responds with [`CreateCustomKeyStoreResponse`](crate::operation::create_custom_key_store::CreateCustomKeyStoreResponse) with field(s):
    ///   - [`custom_key_store_id(Option<::std::string::String>)`](crate::operation::create_custom_key_store::CreateCustomKeyStoreResponse::custom_key_store_id): (undocumented)
    /// - On failure, responds with [`SdkError<CreateCustomKeyStoreError>`](crate::operation::create_custom_key_store::CreateCustomKeyStoreError)
    pub fn create_custom_key_store(&self) -> crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder {
        crate::operation::create_custom_key_store::builders::CreateCustomKeyStoreFluentBuilder::new(self.clone())
    }
}
