// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Do not modify this file. This file is machine generated, and any changes to it will be overwritten.
impl crate::client::Client {
    /// Constructs a fluent builder for the [`RestoreTableToPointInTime`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`billing_mode_override(impl Into<Option<dynamodb::types::BillingMode>>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::billing_mode_override) / [`set_billing_mode_override(Option<dynamodb::types::BillingMode>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::set_billing_mode_override): (undocumented)<br>
    ///   - [`global_secondary_index_override(impl Into<Option<::std::vec::Vec<dynamodb::types::GlobalSecondaryIndex>>>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::global_secondary_index_override) / [`set_global_secondary_index_override(Option<::std::vec::Vec<dynamodb::types::GlobalSecondaryIndex>>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::set_global_secondary_index_override): (undocumented)<br>
    ///   - [`local_secondary_index_override(impl Into<Option<::std::vec::Vec<dynamodb::types::LocalSecondaryIndex>>>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::local_secondary_index_override) / [`set_local_secondary_index_override(Option<::std::vec::Vec<dynamodb::types::LocalSecondaryIndex>>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::set_local_secondary_index_override): (undocumented)<br>
    ///   - [`provisioned_throughput_override(impl Into<Option<dynamodb::types::ProvisionedThroughput>>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::provisioned_throughput_override) / [`set_provisioned_throughput_override(Option<dynamodb::types::ProvisionedThroughput>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::set_provisioned_throughput_override): (undocumented)<br>
    ///   - [`restore_date_time(impl Into<Option<::aws_smithy_types::DateTime>>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::restore_date_time) / [`set_restore_date_time(Option<::aws_smithy_types::DateTime>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::set_restore_date_time): (undocumented)<br>
    ///   - [`sse_specification_override(impl Into<Option<dynamodb::types::SseSpecification>>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::sse_specification_override) / [`set_sse_specification_override(Option<dynamodb::types::SseSpecification>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::set_sse_specification_override): (undocumented)<br>
    ///   - [`source_table_arn(impl Into<Option<::std::string::String>>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::source_table_arn) / [`set_source_table_arn(Option<::std::string::String>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::set_source_table_arn): (undocumented)<br>
    ///   - [`source_table_name(impl Into<Option<::std::string::String>>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::source_table_name) / [`set_source_table_name(Option<::std::string::String>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::set_source_table_name): (undocumented)<br>
    ///   - [`target_table_name(impl Into<Option<::std::string::String>>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::target_table_name) / [`set_target_table_name(Option<::std::string::String>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::set_target_table_name): (undocumented)<br>
    ///   - [`use_latest_restorable_time(impl Into<Option<::std::primitive::bool>>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::use_latest_restorable_time) / [`set_use_latest_restorable_time(Option<::std::primitive::bool>)`](crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::set_use_latest_restorable_time): (undocumented)<br>
    /// - On success, responds with [`RestoreTableToPointInTimeOutput`](crate::operation::restore_table_to_point_in_time::RestoreTableToPointInTimeOutput) with field(s):
    ///   - [`table_description(Option<dynamodb::types::TableDescription>)`](crate::operation::restore_table_to_point_in_time::RestoreTableToPointInTimeOutput::table_description): (undocumented)
    /// - On failure, responds with [`SdkError<RestoreTableToPointInTimeError>`](crate::operation::restore_table_to_point_in_time::RestoreTableToPointInTimeError)
    pub fn restore_table_to_point_in_time(&self) -> crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder {
        crate::operation::restore_table_to_point_in_time::builders::RestoreTableToPointInTimeFluentBuilder::new(self.clone())
    }
}
