// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Do not modify this file. This file is machine generated, and any changes to it will be overwritten.
impl crate::client::Client {
    /// Constructs a fluent builder for the [`UpdateGlobalTableSettings`](crate::operation::update_global_table_settings::builders::UpdateGlobalTableSettingsFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`global_table_billing_mode(impl Into<Option<dynamodb::types::BillingMode>>)`](crate::operation::update_global_table_settings::builders::UpdateGlobalTableSettingsFluentBuilder::global_table_billing_mode) / [`set_global_table_billing_mode(Option<dynamodb::types::BillingMode>)`](crate::operation::update_global_table_settings::builders::UpdateGlobalTableSettingsFluentBuilder::set_global_table_billing_mode): (undocumented)<br>
    ///   - [`global_table_global_secondary_index_settings_update(impl Into<Option<::std::vec::Vec<dynamodb::types::GlobalTableGlobalSecondaryIndexSettingsUpdate>>>)`](crate::operation::update_global_table_settings::builders::UpdateGlobalTableSettingsFluentBuilder::global_table_global_secondary_index_settings_update) / [`set_global_table_global_secondary_index_settings_update(Option<::std::vec::Vec<dynamodb::types::GlobalTableGlobalSecondaryIndexSettingsUpdate>>)`](crate::operation::update_global_table_settings::builders::UpdateGlobalTableSettingsFluentBuilder::set_global_table_global_secondary_index_settings_update): (undocumented)<br>
    ///   - [`global_table_name(impl Into<Option<::std::string::String>>)`](crate::operation::update_global_table_settings::builders::UpdateGlobalTableSettingsFluentBuilder::global_table_name) / [`set_global_table_name(Option<::std::string::String>)`](crate::operation::update_global_table_settings::builders::UpdateGlobalTableSettingsFluentBuilder::set_global_table_name): (undocumented)<br>
    ///   - [`global_table_provisioned_write_capacity_auto_scaling_settings_update(impl Into<Option<dynamodb::types::AutoScalingSettingsUpdate>>)`](crate::operation::update_global_table_settings::builders::UpdateGlobalTableSettingsFluentBuilder::global_table_provisioned_write_capacity_auto_scaling_settings_update) / [`set_global_table_provisioned_write_capacity_auto_scaling_settings_update(Option<dynamodb::types::AutoScalingSettingsUpdate>)`](crate::operation::update_global_table_settings::builders::UpdateGlobalTableSettingsFluentBuilder::set_global_table_provisioned_write_capacity_auto_scaling_settings_update): (undocumented)<br>
    ///   - [`global_table_provisioned_write_capacity_units(impl Into<Option<::std::primitive::i64>>)`](crate::operation::update_global_table_settings::builders::UpdateGlobalTableSettingsFluentBuilder::global_table_provisioned_write_capacity_units) / [`set_global_table_provisioned_write_capacity_units(Option<::std::primitive::i64>)`](crate::operation::update_global_table_settings::builders::UpdateGlobalTableSettingsFluentBuilder::set_global_table_provisioned_write_capacity_units): (undocumented)<br>
    ///   - [`replica_settings_update(impl Into<Option<::std::vec::Vec<dynamodb::types::ReplicaSettingsUpdate>>>)`](crate::operation::update_global_table_settings::builders::UpdateGlobalTableSettingsFluentBuilder::replica_settings_update) / [`set_replica_settings_update(Option<::std::vec::Vec<dynamodb::types::ReplicaSettingsUpdate>>)`](crate::operation::update_global_table_settings::builders::UpdateGlobalTableSettingsFluentBuilder::set_replica_settings_update): (undocumented)<br>
    /// - On success, responds with [`UpdateGlobalTableSettingsOutput`](crate::operation::update_global_table_settings::UpdateGlobalTableSettingsOutput) with field(s):
    ///   - [`global_table_name(Option<::std::string::String>)`](crate::operation::update_global_table_settings::UpdateGlobalTableSettingsOutput::global_table_name): (undocumented)
    ///   - [`replica_settings(Option<::std::vec::Vec<dynamodb::types::ReplicaSettingsDescription>>)`](crate::operation::update_global_table_settings::UpdateGlobalTableSettingsOutput::replica_settings): (undocumented)
    /// - On failure, responds with [`SdkError<UpdateGlobalTableSettingsError>`](crate::operation::update_global_table_settings::UpdateGlobalTableSettingsError)
    pub fn update_global_table_settings(&self) -> crate::operation::update_global_table_settings::builders::UpdateGlobalTableSettingsFluentBuilder {
        crate::operation::update_global_table_settings::builders::UpdateGlobalTableSettingsFluentBuilder::new(self.clone())
    }
}
