// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Do not modify this file. This file is machine generated, and any changes to it will be overwritten.
impl crate::client::Client {
    /// Constructs a fluent builder for the [`UpdateItem`](crate::operation::update_item::builders::UpdateItemFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`attribute_updates(impl Into<Option<::std::collections::HashMap<::std::string::String, dynamodb::types::AttributeValueUpdate>>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::attribute_updates) / [`set_attribute_updates(Option<::std::collections::HashMap<::std::string::String, dynamodb::types::AttributeValueUpdate>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::set_attribute_updates): (undocumented)<br>
    ///   - [`condition_expression(impl Into<Option<::std::string::String>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::condition_expression) / [`set_condition_expression(Option<::std::string::String>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::set_condition_expression): (undocumented)<br>
    ///   - [`conditional_operator(impl Into<Option<dynamodb::types::ConditionalOperator>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::conditional_operator) / [`set_conditional_operator(Option<dynamodb::types::ConditionalOperator>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::set_conditional_operator): (undocumented)<br>
    ///   - [`expected(impl Into<Option<::std::collections::HashMap<::std::string::String, dynamodb::types::ExpectedAttributeValue>>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::expected) / [`set_expected(Option<::std::collections::HashMap<::std::string::String, dynamodb::types::ExpectedAttributeValue>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::set_expected): (undocumented)<br>
    ///   - [`expression_attribute_names(impl Into<Option<::std::collections::HashMap<::std::string::String, ::std::string::String>>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::expression_attribute_names) / [`set_expression_attribute_names(Option<::std::collections::HashMap<::std::string::String, ::std::string::String>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::set_expression_attribute_names): (undocumented)<br>
    ///   - [`expression_attribute_values(impl Into<Option<::std::collections::HashMap<::std::string::String, dynamodb::types::AttributeValue>>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::expression_attribute_values) / [`set_expression_attribute_values(Option<::std::collections::HashMap<::std::string::String, dynamodb::types::AttributeValue>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::set_expression_attribute_values): (undocumented)<br>
    ///   - [`key(impl Into<Option<::std::collections::HashMap<::std::string::String, dynamodb::types::AttributeValue>>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::key) / [`set_key(Option<::std::collections::HashMap<::std::string::String, dynamodb::types::AttributeValue>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::set_key): (undocumented)<br>
    ///   - [`return_consumed_capacity(impl Into<Option<dynamodb::types::ReturnConsumedCapacity>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::return_consumed_capacity) / [`set_return_consumed_capacity(Option<dynamodb::types::ReturnConsumedCapacity>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::set_return_consumed_capacity): (undocumented)<br>
    ///   - [`return_item_collection_metrics(impl Into<Option<dynamodb::types::ReturnItemCollectionMetrics>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::return_item_collection_metrics) / [`set_return_item_collection_metrics(Option<dynamodb::types::ReturnItemCollectionMetrics>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::set_return_item_collection_metrics): (undocumented)<br>
    ///   - [`return_values(impl Into<Option<dynamodb::types::ReturnValue>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::return_values) / [`set_return_values(Option<dynamodb::types::ReturnValue>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::set_return_values): (undocumented)<br>
    ///   - [`table_name(impl Into<Option<::std::string::String>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::table_name) / [`set_table_name(Option<::std::string::String>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::set_table_name): (undocumented)<br>
    ///   - [`update_expression(impl Into<Option<::std::string::String>>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::update_expression) / [`set_update_expression(Option<::std::string::String>)`](crate::operation::update_item::builders::UpdateItemFluentBuilder::set_update_expression): (undocumented)<br>
    /// - On success, responds with [`UpdateItemOutput`](crate::operation::update_item::UpdateItemOutput) with field(s):
    ///   - [`attributes(Option<::std::collections::HashMap<::std::string::String, dynamodb::types::AttributeValue>>)`](crate::operation::update_item::UpdateItemOutput::attributes): (undocumented)
    ///   - [`consumed_capacity(Option<dynamodb::types::ConsumedCapacity>)`](crate::operation::update_item::UpdateItemOutput::consumed_capacity): (undocumented)
    ///   - [`item_collection_metrics(Option<dynamodb::types::ItemCollectionMetrics>)`](crate::operation::update_item::UpdateItemOutput::item_collection_metrics): (undocumented)
    /// - On failure, responds with [`SdkError<UpdateItemError>`](crate::operation::update_item::UpdateItemError)
    pub fn update_item(&self) -> crate::operation::update_item::builders::UpdateItemFluentBuilder {
        crate::operation::update_item::builders::UpdateItemFluentBuilder::new(self.clone())
    }
}
