[package]
name = "dafny_impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
dafny_runtime = { path = "../dafny_runtime_rust"}

[lib]
path = "src/ImplementationFromDafny.rs"